# build with VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle file in /tmp

#sudo docker build -t avi_ansible https://raw.githubusercontent.com/barvinsa/dockerfiles/master/Dockerfile-ansible
#sudo docker run --rm -i -v"/tmp":"/tmp" -v "$(pwd)":"/ansible" -w="/ansible" fenix2:avi_ansible bash

FROM debian:latest

ENV ANSIBLE_HOST_KEY_CHECKING False
ENV ANSIBLE_FORCE_COLOR True

RUN apt-get update && apt-get install -y \
python-dev \
python-pip \
python-virtualenv \
python-cffi \
libssl-dev \
libffi-dev \
openssh-client \
sshpass \
git

RUN pip install \
ansible \
avisdk --upgrade \
pyVmomi \
pyVim \
netaddr \
pysphere \
jmespath \
avimigrationtools \
requests-toolbelt

RUN ansible-galaxy install -f \
avinetworks.avisdk \
avinetworks.avicontroller_vmware

RUN git clone https://github.com/avinetworks/ansible-role-avise-csp.git /root/.ansible/roles/avinetworks.avise_csp

#must have ovftool file in the folder within the build context not an absolute path on the host
# COPY VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle ./
# RUN chmod +x ./VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle
# RUN ./VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle --eulas-agreed --required
