#auto-builds image on dockerhub
#manual build
#sudo docker build -t avi_ansible https://raw.githubusercontent.com/barvinsa/dockerfiles/master/Dockerfile-ansible
#pull and run in the same directory with the playbooks
#docker pull fenix2/avi:ansible
#sudo docker run --rm -it -v"/tmp":"/tmp" -v "$(pwd)":"/ansible" -w="/ansible" fenix2/avi:ansible bash

FROM debian:latest

ENV ANSIBLE_HOST_KEY_CHECKING False
ENV ANSIBLE_FORCE_COLOR True

RUN echo '"\e[A":history-search-backward' >> /root/.inputrc
RUN echo '"\e[B":history-search-forward' >> /root/.inputrc
RUN echo 'alias ll="ls -lA"' >> /root/.bashrc
RUN echo 'export PS1="\[\e[38;5;231m\]\A\[\e[m\]\[\e[38;5;46m\][avi_ansible_container]\[\e[m\]\[\e[38;5;245m\]\w \[\e[m\]\[\e[38;5;250m\]# \[\e[m\]"' >> /root/.bashrc

RUN apt-get update && apt-get install -y \
python-dev \
python-pip \
python-virtualenv \
python-cffi \
libssl-dev \
libffi-dev \
openssh-client \
sshpass \
git

RUN pip install \
ansible \
avisdk --upgrade \
pyVmomi \
pyVim \
netaddr \
pysphere \
jmespath \
avimigrationtools \
requests-toolbelt

RUN ansible-galaxy install -f \
avinetworks.avisdk \
avinetworks.avicontroller_vmware

RUN git clone https://github.com/avinetworks/ansible-role-avise-csp.git /root/.ansible/roles/avinetworks.avise_csp

#build with VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle file in /tmp
#must have ovftool file in the folder within the build context not an absolute path on the host

# COPY VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle ./
# RUN chmod +x ./VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle
# RUN ./VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle --eulas-agreed --required
