#Usage
#container will have yamal-playbook executable
#designed for one time use

FROM debian:latest
ENV ANSIBLE_HOST_KEY_CHECKING False

RUN apt-get update && apt-get install -y \
python \
python-pip \
openssh-client \
sshpass

RUN pip install \
ansible \
#ansible==2.6.11 \
avisdk --upgrade \
pyVmomi \
pyVim \
#for ansible ipaddr()
netaddr \
pysphere

RUN ansible-galaxy install \
avinetworks.avicontroller_vmware \
avinetworks.aviconfig

#if run locally: should upgrade to 4.3!
#RUN chmod +x ~/.ansible/roles/avinetworks.avicontroller_vmware/files/VMware-ovftool-4.1.0-2459827-lin.x86_64.bundle
#RUN ~/.ansible/roles/avinetworks.avicontroller_vmware/files/VMware-ovftool-4.1.0-2459827-lin.x86_64.bundle --eulas-agreed --required

#COPY ansible-hosts /etc/ansible/hosts
RUN mkdir /etc/ansible/
RUN echo 10.57.0.22 > /etc/ansible/hosts

#COPY qlab.pem /root/.ssh/qlab.pem

COPY * ./
